#server:
#  port: 8085
#
#spring:
#  messages:
#    basename: messages,errors
#
#  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
#  h2:
#    console:
#      enabled: true # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-db  # H2 Console의 Path
#
#  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#  datasource:
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/testdb  # H2 접속 정보
#    username: sa # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)

#
#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql

spring:
  datasource:
    url:  jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console






